Repository sandstorm-io/sandstorm, pull requests merged in 2020-07, with the labels that each got.

#3378 Updated cron script for extracting certificates
  docs/administering/ssl.md
Labels: documentation

#3374 Add `-> stream` to a couple capnp methods.
  shell/imports/server/drivers/ip.js
  src/sandstorm/app-index/app-index.c++
  src/sandstorm/sandstorm-http-bridge.c++
  src/sandstorm/supervisor.c++
  src/sandstorm/util.c++
  src/sandstorm/util.capnp
  src/sandstorm/web-session-bridge.c++
  src/sandstorm/web-session.capnp
Labels: ready-for-review

#3381 Fix a typo in the install script and docs
  docs/administering/install-script.md
  install.sh
Labels: documentation, install-config, ready-for-review

#3380 Clarify installer downloads over HTTPS
  docs/administering/install-script.md
  install.sh
Labels: documentation, install-config, ready-for-review

#3325 Add Google Cloud Platform acme support
  shell/imports/client/admin/certificates-client.js
  shell/imports/client/shell.html
  shell/package.json
Labels: enhancement, install-config, ready-for-review

#3366 Improve the "unknown host" error page.
  src/sandstorm/gateway.c++
Labels: enhancement, ready-for-review, usability

#3382 Source web page was updated with the new script
  docs/administering/ssl.md
Labels: documentation
