Repository sandstorm-io/sandstorm, pull requests merged in 2020-02, with the labels that each got.

#3187 Doc action
  .github/workflows/doc-prod.yml
  docs/README.md
  docs/generate.sh
Labels: documentation

#3100 Depend on network-online.service instead of network.service
  install.sh
Labels: self-hosting

#3162 Adapt sync-langs.py for Python 3
  shell/i18n/sync-langs.py
Labels: shell

#3200 Update vagrant-spk stack list to reflect master
  docs/vagrant-spk/platform-stacks.md
Labels: documentation

#3201 Remove vagrant-spk design doc
  docs/developing.md
  docs/vagrant-spk/design.md
  mkdocs.yml
Labels: documentation

#3216 Clarify what one might use for a nounPhrase
  docs/vagrant-spk/packaging-tutorial.md
Labels: documentation

#3217 Docs: "Last few months" > "In the past"
  docs/administering/wildcard.md
Labels: documentation

#3214 Docs: Change vagrant-spk port to 6090
  docs/developing/debugging.md
  docs/vagrant-spk/packaging-tutorial-meteor.md
  docs/vagrant-spk/packaging-tutorial.md
  docs/vagrant-spk/platform-stacks.md
Labels: documentation

#3206 Fix Vagrantfile's Windows RAM calculation
  Vagrantfile
Labels: ready-for-review, sandstorm-dev

#3202 Fix typo in about page
  shell/i18n/en.i18n.json
Labels: ready-for-review, shell

#3175 Mass Transfer to translateable, and translate to Finnish.
  shell/client/grain/grainlist.html
  shell/client/transfers-client.js
  shell/client/transfers.html
  shell/i18n/en.i18n.json
  shell/i18n/fi.i18n.json
Labels: ready-for-review, shell

#3227 Schedule tests: close the grain window when we're done.
  tests/apps/schedule.js
Labels: ready-for-review, sandstorm-dev

#3221 Implement support for AppHooks
  Makefile
  meteor-testapp/capnp/meteor-testapp.capnp
  meteor-testapp/sandstorm-pkgdef.capnp
  meteor-testapp/server/main.js
  src/sandstorm/sandstorm-http-bridge.c++
  tests/commands/uploadMeteorTestApp.js
  tests/tests/account-settings.js
  tests/tests/appHooks.js
Labels: app-platform, ready-for-review

#3236 Update zh-CN language file
  shell/i18n/zh-CN.i18n.json
Labels: shell

#3222 Allow apps using the bridge to respond to powerbox requests & offers
  docs/developing/powerbox.md
  src/sandstorm/sandstorm-http-bridge-internal.capnp
  src/sandstorm/sandstorm-http-bridge.c++
  src/sandstorm/sandstorm-http-bridge.capnp
Labels: app-platform, ready-for-review

#3155 Support "add to home screen" on mobile browsers.
  shell/client/main.html
  shell/imports/client/00-startup.js
  shell/public/manifest.json
  shell/public/pwa-service-worker.js
  shell/public/sandstorm-gradient-logo.png
Labels: enhancement, ready-for-review

#3244 Docs: Remove Google Fonts
  docs/extra.css
  docs/sandstorm_readthedocs_modified_theme/base.html
  docs/sandstorm_readthedocs_modified_theme/css/theme.css
Labels: documentation
