Repository sandstorm-io/sandstorm, pull requests merged in 2020-10, with the labels that each got.

#3455 Fix getGrainTitle example
  docs/developing/path.md
Labels: documentation

#3445 Fix #3443
  shell/imports/server/scheduled-job.js
Labels: app-platform, ready-for-review

#3446 Update zh-CN language file
  shell/i18n/zh-CN.i18n.json
Labels: ready-for-review, shell

#3449 Add deSEC DNS provider
  shell/imports/client/admin/certificates-client.js
  shell/imports/client/shell.html
  shell/npm-shrinkwrap.json
  shell/package.json
Labels: enhancement, install-config, ready-for-review

#3398 Freeze grains during backup
  src/sandstorm/backend.c++
  src/sandstorm/backend.h
  src/sandstorm/cgroup2.c++
  src/sandstorm/cgroup2.h
Labels: enhancement, ready-for-review

#3456 Correctly handle responses to HEAD requests that use Content-Length
  src/sandstorm/sandstorm-http-bridge.c++
Labels: app-platform, ready-for-review

#3458 cgroups: don't fail to back up if cgroup.freeze doesn't exist.
  src/sandstorm/cgroup2.c++
  src/sandstorm/cgroup2.h
Labels: app-platform, bug, ready-for-review
