Repository sandstorm-io/sandstorm, pull requests merged in 2020-11, with the labels that each got.

#3461 Install docs: add strace to the dependency list.
  docs/install.md
Labels: documentation

#3470 Mention the app-requests label in the CONTRIBUTING doc.
  CONTRIBUTING.md
Labels: documentation

#3447 Fix a path traversal vulnerability involving static publishing.
  src/sandstorm/supervisor.c++
  src/sandstorm/util-test.c++
  src/sandstorm/util.c++
  src/sandstorm/util.h
Labels: app-platform, ready-for-review, security

#3460 Fix a build error affecting some systems.
  src/sandstorm/sandstorm-http-bridge.c++
Labels: app-platform, bug, ready-for-review, sandstorm-dev

#3462 make-bundle.sh: use the same compiler as the rest of the build.
  Makefile
  make-bundle.sh
Labels: ready-for-review, sandstorm-dev

#3465 Finish removing legacy HTTP access via HackSession
  .github/workflows/build.yml
  shell/imports/sandstorm-db/db.js
  shell/imports/server/drivers/external-ui-view.js
  shell/imports/server/hack-session.js
  shell/imports/server/migrations.js
Labels: app-platform, ready-for-review, security

#3471 Update Dutch translation
  shell/i18n/nl.i18n.json
Labels: ready-for-review, shell
