Repository sandstorm-io/sandstorm, pull requests merged in 2020-03, with the labels that each got.

#3241 Actions: Don't upload every build, BUILD 0
  .github/workflows/build.yml
Labels: ready-for-review, sandstorm-dev

#3251 Docs: Remove calls to email
  docs/administering/active-directory.md
  docs/administering/faq.md
  docs/administering/for-work.md
  docs/administering/guide.md
  docs/administering/reverse-proxy.md
  docs/developing.md
  docs/developing/handbook.md
  docs/developing/publishing-apps.md
  docs/install.md
  docs/vagrant-spk/packaging-tutorial-meteor.md
Labels: documentation

#3253 Docs: Remove offers of services we don't offer
  docs/developing.md
Labels: documentation

#3256 powerbox-server: dedup code from async-helpers.
  shell/imports/sandstorm-ui-powerbox/powerbox-server.js
Labels: app-platform, ready-for-review

#3247 grain.html: use blaze's else-if support.
  shell/imports/client/grain.html
Labels: ready-for-review, shell

#3246 Update docs theme to enable greater depth
  docs/analytics.js
  docs/sandstorm_readthedocs_modified_theme/404.html
  docs/sandstorm_readthedocs_modified_theme/base.html
  docs/sandstorm_readthedocs_modified_theme/breadcrumbs.html
  docs/sandstorm_readthedocs_modified_theme/css/theme.css
  docs/sandstorm_readthedocs_modified_theme/css/theme_extra.css
  docs/sandstorm_readthedocs_modified_theme/footer.html
  docs/sandstorm_readthedocs_modified_theme/img/favicon.ico
  docs/sandstorm_readthedocs_modified_theme/js/jquery-2.1.1.min.js
  docs/sandstorm_readthedocs_modified_theme/js/modernizr-2.8.3.min.js
  docs/sandstorm_readthedocs_modified_theme/js/theme.js
  docs/sandstorm_readthedocs_modified_theme/main.html
  docs/sandstorm_readthedocs_modified_theme/mkdocs_theme.yml
  docs/sandstorm_readthedocs_modified_theme/nav.html
  docs/sandstorm_readthedocs_modified_theme/search.html
  docs/sandstorm_readthedocs_modified_theme/searchbox.html
  docs/sandstorm_readthedocs_modified_theme/sitename.html
  docs/sandstorm_readthedocs_modified_theme/toc.html
  docs/sandstorm_readthedocs_modified_theme/versions.html
  mkdocs.yml
Labels: documentation

#3257 Reorganize docs and add back scroll bar
  docs/developing/handbook.md
  docs/extra.css
  mkdocs.yml
Labels: documentation

#3258 Docs: Square off search box
  docs/sandstorm_readthedocs_modified_theme/css/theme_extra.css
Labels: documentation

#3268 Update nl.i80n.json
  shell/i18n/nl.i18n.json
Labels: ready-for-review, shell

#3252 Have "send feedback" link to GitHub issues
  shell/imports/client/accounts/login-buttons.html
Labels: ready-for-review, shell

#3266 Remove obsolete `socketPath` constant in backend.capnp
  src/sandstorm/backend.capnp
Labels: ready-for-review

#3255 Fuse: list write operations explicitly, default to ENOSYS.
  src/sandstorm/fuse.c++
Labels: app-packaging, ready-for-review

#3262 Spk dev: display BASE_URL to the user.
  src/sandstorm/config.c++
  src/sandstorm/config.h
  src/sandstorm/run-bundle.c++
  src/sandstorm/spk.c++
Labels: app-packaging, enhancement, ready-for-review

#3242 `meteor add typescript`
  Makefile
  shell/.meteor/packages
  shell/.meteor/versions
  shell/client/main.ts
  shell/server/main.ts
Labels: ready-for-review, shell

#3274 Add basic eslint config, fix some issues.
  .github/workflows/build.yml
  Makefile
  shell/.eslintrc.yml
  shell/.meteor/versions
  shell/imports/client/accounts/login-buttons.js
  shell/imports/client/contacts.js
  shell/imports/client/grain/grainview-list.js
  shell/imports/client/grain/grainview.js
  shell/imports/server/sandcats.js
  shell/npm-shrinkwrap.json
  shell/package.json
Labels: ready-for-review, shell

#3278 Remove spacejam dependency from tests/
  tests/package.json
Labels: ready-for-review, sandstorm-dev

#3283 Adopt & fix most of the rules from eslint:recommended
  shell/.eslintrc.yml
  shell/imports/blackrock-payments/client/payments-client.js
  shell/imports/blackrock-payments/server/payments-server.js
  shell/imports/client/accounts/account-settings.js
  shell/imports/client/download-file.js
  shell/imports/client/grain-client.js
  shell/imports/client/grain/grainview-list.js
  shell/imports/client/grain/grainview.js
  shell/imports/dates.js
  shell/imports/install.js
  shell/imports/sandstorm-db/db.js
  shell/imports/sandstorm-identicons/helpers.js
  shell/imports/sandstorm-identicons/identicon.js
  shell/imports/sandstorm-permissions/permissions.js
  shell/imports/server/accounts/credentials/credentials-server.js
  shell/imports/server/accounts/ldap.js
  shell/imports/server/accounts/saml-utils.js
  shell/imports/server/backend.js
  shell/imports/server/core.js
  shell/imports/server/drivers/external-ui-view.js
  shell/imports/server/drivers/ip.js
  shell/imports/server/drivers/mail.js
  shell/imports/server/gateway-router.js
  shell/imports/server/header-whitelist.js
  shell/imports/server/identity.js
  shell/imports/server/install-server.js
  shell/imports/server/persistent.js
  shell/imports/server/sandcats.js
  shell/imports/server/shell-server.js
  shell/imports/server/startup.js
  shell/imports/server/static-asset.js
  shell/imports/server/transfers-server.js
Labels: ready-for-review, shell
