Repository sandstorm-io/sandstorm, pull requests merged in 2020-08, with the labels that each got.

#3386 Remove stray HTTPS = sandcats.io in installer text
  install.sh
Labels: install-config, ready-for-review

#3377 Add a 'clone grain' button.
  .github/workflows/build.yml
  icons/copy.svg
  shell/client/styles/_topbar.scss
  shell/i18n/en.i18n.json
  shell/imports/client/grain-client.js
  shell/imports/client/grain.html
Labels: enhancement, ready-for-review, shell, usability

#3369 Put grains in cgroups.
  src/sandstorm/backend.c++
  src/sandstorm/backend.h
  src/sandstorm/cgroup2.c++
  src/sandstorm/cgroup2.h
  src/sandstorm/run-bundle.c++
Labels: app-platform, enhancement, ready-for-review

#3393 Fix SVGs in App Index review interface
  src/sandstorm/app-index/app-index.capnp
  src/sandstorm/app-index/review.html
Labels: bug, ready-for-review

#3400 Update Finnish translation.
  shell/i18n/fi.i18n.json
Labels: ready-for-review, shell

#3408 Fix incorrect formatting of qValue in accept header.
  shell/imports/server/drivers/external-ui-view.js
Labels: app-platform, bug, ready-for-review

#3407 Disable HTTP access through hack-session.
  shell/imports/sandstorm-db/db.js
  shell/imports/server/hack-session.js
  src/sandstorm/hack-session.capnp
Labels: app-platform, ready-for-review, security

#3409 Content security policy for grains.
  src/sandstorm/config.c++
  src/sandstorm/config.h
  src/sandstorm/gateway.c++
  src/sandstorm/gateway.h
  src/sandstorm/run-bundle.c++
  src/sandstorm/web-session-bridge.c++
  src/sandstorm/web-session-bridge.h
Labels: app-platform, enhancement, ready-for-review, security

#3414 Remove unused iptables header rule.
  src/sandstorm/ip_tables.ekam-rule
  src/sandstorm/supervisor.c++
Labels: ready-for-review

#3420 Remove unused variables
  .github/workflows/build.yml
  shell/imports/server/transfers-server.js
Labels: ready-for-review, shell

#3421 Some improvements to our eslint config
  shell/.eslintrc.yml
  shell/npm-shrinkwrap.json
  shell/package.json
Labels: ready-for-review, shell
