Repository sandstorm-io/sandstorm, pull requests merged in 2020-01, with the labels that each got.

#3176 Spec out a solution to #3027
  src/sandstorm/package.capnp
  src/sandstorm/sandstorm-http-bridge.capnp
Labels: app-platform

#3183 install.sh: Don't ask the user whether to report E_CURL_MISSING
  install.sh
Labels: install-config

#3172 Cron API
  shell/packages/sandstorm-db/db.js
  shell/packages/sandstorm-db/package.js
  shell/packages/sandstorm-db/scheduled-jobs-db.js
  shell/server/core.js
  shell/server/scheduled-job.js
  shell/shared/testing.js
  src/sandstorm/grain.capnp
  src/sandstorm/supervisor.c++
  src/sandstorm/supervisor.capnp
  src/sandstorm/test-app/test-app.c++
  src/sandstorm/test-app/test-app.capnp
  src/sandstorm/test-app/test-app.html
  tests/apps/schedule.js
Labels: app-platform

#2922 implement SandstormApi.schedulePeriodic()
  shell/packages/sandstorm-db/db.js
  shell/packages/sandstorm-db/package.js
  shell/packages/sandstorm-db/scheduled-jobs-db.js
  shell/server/core.js
  shell/server/scheduled-job.js
  src/sandstorm/grain.capnp
  src/sandstorm/sandstorm.ekam-manifest
  src/sandstorm/scheduled-job-impl.capnp
  src/sandstorm/supervisor.c++
  src/sandstorm/supervisor.capnp
  src/sandstorm/util.capnp
Labels: app-platform

#3169 Docs: Update "wrench icon" with "console icon"
  docs/developing/raw-packaging-guide.md
Labels: documentation

#3193 Add -DKJ_STD_COMPAT to C(XX)FLAGS.
  Makefile
Labels: sandstorm-dev
