Repository sandstorm-io/sandstorm, pull requests merged in 2020-12, with the labels that each got.

#3452 OpenID Connect Login Provider
  .github/workflows/build.yml
  .gitignore
  Makefile
  icons/openid-color.svg
  icons/openid.svg
  shell/client/styles/_account.scss
  shell/client/styles/_admin-users.scss
  shell/client/styles/_partials.scss
  shell/i18n/en.i18n.json
  shell/imports/client/accounts/login-buttons.js
  shell/imports/client/admin/login-providers.html
  shell/imports/client/admin/login-providers.js
  shell/imports/client/admin/organization-client.js
  shell/imports/client/admin/organization.html
  shell/imports/client/setup-wizard/wizard.html
  shell/imports/client/setup-wizard/wizard.js
  shell/imports/client/shell.html
  shell/imports/oidc/oidc-client.js
  shell/imports/oidc/oidc-server.js
  shell/imports/sandstorm-db/db.js
  shell/imports/sandstorm-db/profile.js
  shell/imports/server/accounts/accounts-server.js
  shell/imports/server/admin-server.js
  shell/imports/server/migrations.js
  shell/imports/shared/admin.js
  shell/npm-shrinkwrap.json
  shell/package.json
  shell/server/main.ts
  src/sandstorm/run-bundle.c++
Labels: enhancement, ready-for-review, shell

#3475 Generate JavaScript source maps.
  shell/.meteor/packages
  shell/.meteor/versions
Labels: ready-for-review, sandstorm-dev

#3476 sandstorm-http-bridge: Fix some build errors against capnp master.
  src/sandstorm/sandstorm-http-bridge.c++
Labels: app-platform, ready-for-review

#3473 Fix some regressions re: the recent static publishng symlink fix.
  src/sandstorm/supervisor.c++
  src/sandstorm/util-test.c++
  src/sandstorm/util.c++
  src/sandstorm/util.h
Labels: app-platform, bug, ready-for-review, security

#3485 Fix #3484
  shell/imports/client/setup-wizard/wizard.js
Labels: bug, install-config, ready-for-review
