Repository sandstorm-io/sandstorm, pull requests merged in 2021-01, with the labels that each got.

#3486 Fix a typo in a comment in the test script.
  tests/run-tests.sh
Labels: ready-for-review, sandstorm-dev

#3493 Fix some linter warnings
  .github/workflows/build.yml
  shell/imports/blackrock-payments/client/billingPrompt.js
  shell/imports/blackrock-payments/client/billingSettings.js
  shell/imports/blackrock-payments/client/payments-api-client.js
  shell/imports/blackrock-payments/client/payments-client.js
Labels: ready-for-review, sandstorm-dev

#3492 Fix tests/grain.js tests using Chromium 80 and Debian 10
  tests/nightwatch.json
Labels: ready-for-review, sandstorm-dev

#3483 Fix #3482
  shell/imports/server/drivers/external-ui-view.js
  shell/imports/server/gateway-router.js
  shell/imports/server/web-session.ts
Labels: app-platform, ready-for-review

#3481 Makefile: add missing dependency meteor-testapp-dev -> meteor-spk
  Makefile
Labels: ready-for-review, sandstorm-dev

#3463 Add pathname and hash support for shared URLs
  docs/developing/path.md
  shell/imports/client/grain-client.js
  shell/imports/client/grain/grainview.js
  tests/tests/postmessage-api.js
Labels: app-platform, enhancement, ready-for-review
