Repository sandstorm-io/sandstorm, pull requests merged in 2021-05, with the labels that each got.

#3518 Fix a typo in a variable name.
  shell/imports/server/scheduled-job.js
Labels: bug, ready-for-review

#3514 Update upload-artifact to v2
  .github/workflows/build.yml
Labels: ready-for-review, sandstorm-dev

#3525 Update IRC channel in docs
  CONTRIBUTING.md
  docs/administering/install-troubleshooting.md
  docs/developing.md
  docs/developing/troubleshooting.md
  docs/sandstorm_readthedocs_modified_theme/footer.html
Labels: documentation, ready-for-review
