Repository sandstorm-io/sandstorm, pull requests merged in 2021-07, with the labels that each got.

#3532 Add PowerDNS plugin for ACME.js
  shell/imports/client/admin/certificates-client.js
  shell/imports/client/shell.html
  shell/npm-shrinkwrap.json
  shell/package.json
Labels: enhancement, install-config, ready-for-review

#3533 Remove remnants of old shell dev workflow.
  shell/run-dev.sh
  src/sandstorm/run-bundle.c++
Labels: ready-for-review, sandstorm-dev

#3539 CSP: Set worker-src to none
  src/sandstorm/web-session-bridge.c++
Labels: app-platform, ready-for-review, security

#3543 Update doc link to allowed non-web-browser User-Agent strings
  docs/developing/http-apis.md
Labels: documentation
