Repository sandstorm-io/sandstorm, pull requests merged in 2021-11, with the labels that each got.

#3435 Add a backup button to the grain list.
  shell/i18n/en.i18n.json
  shell/i18n/fi.i18n.json
  shell/i18n/fr.i18n.json
  shell/i18n/nl.i18n.json
  shell/i18n/zh-CN.i18n.json
  shell/i18n/zh-TW.i18n.json
  shell/imports/client/backups.ts
  shell/imports/client/grain-client.js
  shell/imports/client/grain/grainlist-client.js
  shell/imports/client/grain/grainlist.html
  shell/imports/client/meteor-call-promise.ts
Labels: usability, shell, ready-for-review

#3576 Fix the icon font generation
  Makefile
  icons/Gruntfile.js
  icons/package.json
Labels: shell, ready-for-review

#3579 More Vagrantfile improvements
  Vagrantfile
Labels: install-config, ready-for-review

#3583 Make use of Pipe::make() helper from utils
  src/sandstorm/run-bundle.c++
  src/sandstorm/util-test.c++
Labels: ready-for-review

#3587 Factor out some common sandbox setup code
  src/sandstorm/backup.c++
  src/sandstorm/sandbox.c++
  src/sandstorm/sandbox.h
  src/sandstorm/supervisor.c++
Labels: ready-for-review

#3588 Stop installing a very old version of meteor
  .github/workflows/build.yml
  docs/install.md
Labels: sandstorm-dev

#3591 Update doc: Installing from source now requires python3
  .github/workflows/build.yml
  docs/install.md
Labels: documentation, install-config

#3593 Docs: Provide fix for inotify limit issue
  docs/administering/faq.md
Labels: documentation
