Repository sandstorm-io/sandstorm, pull requests merged in 2021-10, with the labels that each got.

#3558 Remove remaining references to phantomjs
  .gitignore
  tests/nightwatch.json
Labels: sandstorm-dev, ready-for-review

#3560 make ci-clean: delete test-app.spk
  Makefile
Labels: sandstorm-dev, ready-for-review

#3562 Fix an incorrect comment in the test-app
  src/sandstorm/test-app/test-app.c++
Labels: sandstorm-dev, ready-for-review

#3570 Fix typo on login providers page
  shell/i18n/en.i18n.json
Labels: shell, ready-for-review

#3575 Add a workflow for previewing doc changes
  .github/workflows/doc-ci.yml
  docs/README.md
  docs/generate.sh
  docs/requirements.txt
Labels: documentation

#3577 install.md: remove duplicate mention of strace
  docs/install.md
Labels: documentation
