Repository sandstorm-io/sandstorm, pull requests merged in 2021-09, with the labels that each got.

#3555 Fix typo
  docs/administering/faq.md
Labels: documentation

#3549 Add a SECURITY.md file
  SECURITY.md
Labels: documentation, ready-for-review, security

#3551 Artifacts from failing tests get valid filenames
  tests/utils.js
Labels: sandstorm-dev, ready-for-review

#3552 Add more owncloud/nextcloud client headers
  src/sandstorm/web-session.capnp
Labels: app-platform, ready-for-review

#3556 Update installer-tests/README.md to refer to stodgy-tester
  installer-tests/README.md
  installer-tests/prepare-for-tests.sh
Labels: sandstorm-dev, ready-for-review

#3564 Update documentation on installing from source
  docs/install.md
Labels: documentation

#3566 Update build instructions for Fedora (closes #3565)
  docs/install.md
Labels: documentation

#3567 Improve docs regarding test suite
  docs/install.md
  tests/README.md
Labels: documentation, sandstorm-dev
