Repository sandstorm-io/sandstorm, pull requests merged in 2022-07, with the labels that each got.

#3616 Mark known-failing tests as "expected to fail," disabling them by default.
  .github/workflows/build.yml
  tests/README.md
  tests/apps/schedule.js
  tests/run-local.sh
  tests/tests/account.js
  tests/tests/appHooks.js
  tests/tests/basic.js
  tests/utils.js
Labels: sandstorm-dev, ready-for-review

#3645 Docs: Fix GPG export instructions
  docs/developing/publishing-apps.md
Labels: documentation

#3642 Docs: Troubleshoot "disallow collab" on install
  docs/administering/install-troubleshooting.md
Labels: documentation, ready-for-review

#3647 Docs: delete graphviz
  .github/workflows/doc-ci.yml
  docs/generate.sh
  docs/requirements.txt
  docs/using/communication_overview_http_app.svg
  docs/using/communication_overview_native_app.svg
  docs/using/how-it-works.md
  mkdocs.yml
Labels: documentation

#3648 Docs: Delete B rating comment
  docs/administering/sandcats-https.md
Labels: documentation

#3652 Minor fix
  docs/developing/troubleshooting.md
Labels: documentation
