Repository sandstorm-io/sandstorm, pull requests merged in 2022-08, with the labels that each got.

#3655 Docs: Minor spelling fix
  docs/developing/debugging.md
Labels: documentation

#3656 Document ALLOW_LEGACY_RELAXED_CSP
  docs/administering/config-file.md
Labels: documentation

#3637 Apply backpressure when installing packages.
  .github/workflows/build.yml
  shell/imports/server/install-server.js
  shell/imports/server/installer.js
Labels: install-config, ready-for-review

#3639 release.sh: automatically push to master
  release.sh
Labels: sandstorm-dev, ready-for-review

#3640 Change support@ in setup wizard to dev list link
  shell/imports/client/setup-wizard/wizard.html
Labels: install-config, ready-for-review

#3643 Google Apps for Work is Workspace
  docs/administering/for-work.md
  shell/i18n/en.i18n.json
  shell/i18n/fi.i18n.json
  shell/i18n/fr.i18n.json
  shell/i18n/nl.i18n.json
  shell/i18n/zh-CN.i18n.json
  shell/i18n/zh-TW.i18n.json
Labels: shell, ready-for-review

#3649 Support setting the foreground color for offer iframes.
  docs/developing/http-apis.md
  shell/imports/client/grain-client.js
  shell/public/offer-template.html
Labels: app-platform, ready-for-review

#3650 Block webrtc
  src/sandstorm/web-session-bridge.c++
Labels: app-platform, ready-for-review, security
