Repository sandstorm-io/sandstorm, pull requests merged in 2022-11, with the labels that each got.

#3671 Add sponsor button to repo
  .github/FUNDING.yml
Labels: documentation, ready-for-review

#3670 Improvements to experimental seccomp filter
  src/sandstorm/seccomp-bpf/filter.s
Labels: app-platform, ready-for-review, security

#3669 Report install failures to Alpha
  install.sh
Labels: install-config, ready-for-review
